catalog/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index, name="index"),
    # This view will be implemented as a Class.
    # as_view() does all the work of creating an
    # instance of the class, and making sure that
    # the right handler methods are called for incoming HTTP requests
    url(r'^books/$', views.BookListView.as_view(), name='books'),
    # book-detail url mapper
    url(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name="book-detail"),
    # authors url mapper
    url(r'^authors/$', views.AuthorListView.as_view(), name="authors"),
    # author-detail url mapper
    url(r'^author/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name="author-detail"),
]

locallibrary/urls.py
from django.conf.urls import url
from django.contrib import admin

# Use include() to add URLS from the catalog application
from django.conf.urls import include

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Maps all urls with the pattern admin/ to the module admin.site.urls
    url(r'^admin/', admin.site.urls),
]

urlpatterns += [
    # Maps all urls with the pattern catalog/ to the module catalog.urls
    # the file with the relative URL /catalog/urls.py
    url(r'^catalog/', include('catalog.urls')),
]

urlpatterns += [
    # Redirect empty url to /catalog/
    url(r'^$', RedirectView.as_view(url='/catalog/', permanent=True)),
]

# Enable serving of static files
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
# Used to generate URLs by reversing the URL patterns
from django.urls import reverse
# Required for unique book instances
import uuid


# Create your models here.
class Genre(models.Model):
    """
    Model representing a book genre (e.g. Science Fiction, Non Fiction).
    """
    name = models.CharField(
        max_length=200,
        help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)"
    )

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.name


class Language(models.Model):
    """
    Model representing a Language (e.g. English, French, Japanese, etc.)
    """
    name = models.CharField(
        max_length=200,
        help_text="Enter a the book's natural language (e.g. English, French, Japanese etc.)"
    )

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.name


class Author(models.Model):
    """
    Model representing an author.
    """
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    def get_absolute_url(self):
        """
        Returns the url to access a particular author instance.
        """
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Author object.
        """
        return "{0} ({1})".format(self.last_name, self.first_name)


class Book(models.Model):
    """
    Model representing a book (but not a specific copy of a book).
    """
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the book")

    isbn = models.CharField(
        'ISBN',
        max_length=13,
        help_text="13 Character <a href='https://www.isbn-international.org/content/what-isbn'>ISBN number</a>"
    )

    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.title

    def get_absolute_url(self):
        """
        Returns the url to access a particular book instance.
        """
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        """
        Creates a string for the Genre.
        This is required to display genre in Admin.
        """
        return ', '.join([genre.name for genre in self.genre.all()[:3]])

    display_genre.short_description = 'Genre'


class BookInstance(models.Model):
    """
    Model representing a specific copy of a book (i.e. that can be borrowed from the library).
    """
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text="Unique ID for this particular book across whole library"
    )

    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text="Book availability"
    )

    class Meta:
        # Define an order
        # Order records by due_date when they are returned in a query.
        ordering = ["due_back"]

    def __str__(self):
        """
        String for representing the Model object
        """
        return "{0} ({1})".format(self.id, self.book.title)

catalog/views.py
from django.shortcuts import render
from django.views import generic
from .models import Book, Author, BookInstance, Genre


# Create your views here.
def index(request):
    """
    View function for home page of site.
    """
    # Generate count of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.count()    # The 'all()' is implied by default.
    genres = Genre.objects.count()

    # Number of visits to this view as counted in the session variable
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    return render(request,
                  'index.html',
                  context={
                      'num_books': num_books,
                      'num_instances': num_instances,
                      'num_instances_available': num_instances_available,
                      'num_authors': num_authors,
                      'genres': genres,
                      'num_visits': num_visits
                  })


class BookListView(generic.ListView):
    """
    View function to list all books
    """
    model = Book
    # Our own name for the list as a template variable
    context_object_name = 'book_list'
    template_name = 'catalog/book_list.html'
    paginate_by = 10


class BookDetailView(generic.DetailView):
    """
    View function to display a book's details
    """
    model = Book
    context_object_name = 'book'
    template_name = 'catalog/book_detail.html'


class AuthorListView(generic.ListView):
    """
    View function to display an author's details
    """
    model = Author
    context_object_name = 'author_list'
    template_name = 'catalog/author_list.html'
    paginate_by = 10


class AuthorDetailView(generic.DetailView):
    """
    View function to display an author's details
    """
    model = Author
    context_object_name = 'author'
    template_name = 'catalog/author-detail.html'

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    <title>Local Library</title>
    {% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <!-- Add additional CSS in static file after loading the 'static' library -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">

</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
                {% block sidebar %}
                <ul class="sidebar-nav">
                    <li><a href="{% url 'index' %}">Home</a></li>
                    <li><a href="{% url 'books' %}">All books</a></li>
                    <li><a href="{% url 'authors' %}">All authors</a></li>
                </ul>
                {% endblock %}
            </div>
            <div class="col-sm-10">
                {% block content %}{% endblock %}
                {% block pagination %}
                    {% if is_paginated %}
                        <div class="pagination">
                            <span class="page-links">
                                {% if page_obj.has_previous %}
                                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                                {% endif %}
                                <span class="page-current">
                                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                                </span>
                                {% if page_obj.has_next %}
                                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                                {% endif %}
                            </span>
                        </div>
                    {% endif %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

catalog/templates/catalog/author-detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Author: {{ author }}</h1>

  <p>{{author.date_of_birth}} - {% if author.date_of_death %}{{author.date_of_death}}{% endif %}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Books</h4>
    {#  reverse lookup for book instances from an author instance  #}
    <dl>
        {% for book in author.book_set.all %}
        <hr>
            <dt><a href="{% url 'book-detail' book.pk %}"> {{book.title}} </a>({{ book.bookinstance_set.count }})</dt>
            <dd><p><strong>Summary:</strong> {{book.summary}}</p></dd>
        {% endfor %}
    </dl>
  </div>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Authors</h1>

    {% if author_list %}
    <ul>

      {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">
            {{ author }}
            ({% if author.date_of_birth %}
                {{author.date_of_birth}}
            {% endif %}
                -
            {% if author.date_of_death %}
                {{author.date_of_death}}
            {% endif %})
        </a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no authors available.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p>
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong>
      {% for genre in book.genre.all %}
        {{ genre }}
        {% if not forloop.last %}, {% endif %}
      {% endfor %}
  </p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>
    {#  reverse lookup for book copy instances from a book instance  #}
    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}
                text-success
            {% elif copy.status == 'm' %}
                text-danger
            {% else %}
                text-warning
            {% endif %}">
        {{ copy.get_status_display }}
    </p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Book List</h1>

    {% if book_list %}
    <ul>

      {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}

{% block title %}
<title>Local Library Home</title>
{%  endblock %}

{% block content %}
<h1>Local Library Home</h1>
<p>Welcome to <em>LocalLibrary</em>, a very basic Django website developed as a tutorial example on the Mozilla Developer Network.</p>
<h2>Dynamic content</h2>

<p>The library has the following record counts:</p>
<ul>
    <li>
        <strong>Books:</strong> {{ num_books }}
    </li>
    <li>
        <strong>Copies:</strong> {{ num_instances }}
    </li>
    <li>
        <strong>Copies available: </strong> {{ num_instances_available }}
    </li>
    <li>
        <strong>Authors: </strong> {{ num_authors }}
    </li>
    <li>
        <strong>Genres: </strong> {{ genres }}
    </li>
</ul>

<p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>
{% endblock %}